name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.6.1
      with:
        version: "15"
    - uses: actions/checkout@v2
    - name: tests
      run: ./tests/run.sh ci
    - name: coverage
      uses: codecov/codecov-action@v3
      with:
        gcov: true
