name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: tests
      run: ./tests/run.sh
    - name: coverage
      uses: codecov/codecov-action@v3
      with:
        gcov: true
