name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: tests
      run: ./tests/run.sh
    - name: example build gcc debug
      run: ./example/build.sh gcc debug
    - name: example build gcc release
      run: ./example/build.sh gcc release
    - name: example build clang debug
      run: ./example/build.sh clang debug
    - name: example build clang release
      run: ./example/build.sh clang release    
    - name: coverage
      uses: codecov/codecov-action@v3
      with:
        gcov: true
