name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: example build debug
      run: ./example/build.sh debug
    - name: example build release
      run: ./example/build.sh release
    - name: tests
      run: ./tests/build.sh
    - name: coverage
      uses: codecov/codecov-action@v3
      with:
        gcov: true
