name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Install LLVM (for coverage)
      run: sudo apt install -y llvm
    - uses: actions/checkout@v2
    - name: tests
      run: ./tests/run.sh ci
    - name: coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./tests/coverage.txt

  build-windows:
    runs-on: windows-2022
    steps:
    - name: Install LLVM (for coverage)
      run: curl -fsSL -o "LLVM-15.0.6-win64.exe" "https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/LLVM-15.0.6-win64.exe"
        "LLVM-15.0.6-win64.exe" /S
    - uses: actions/checkout@v2
    - name: tests
      run: ./tests/run.bat ci
    - name: coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./tests/coverage.txt
